### ISSUE TITLE
Add option to remove a connection / interface

### ISSUE THREAD

**Issue by isonet** [Schlipak/interface-tele-tps#46]

**Comment by isonet** [comment]
@Schlipak Tu peux faire ça? Je sais pas trop comment le réaliser. Juste un petit button ou un truc comme ca dans la sidebar pour pouvoir supprimer une interface.

**Comment by Schlipak** [comment]
Okay je verrais ça dès que je peux, je suis pas encore chez moi mais dès ce soir pas de problème.
